"""empty message

Revision ID: 255ef53484fb
Revises: 3686839edec2
Create Date: 2025-05-18 17:09:51.307246

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '255ef53484fb'
down_revision = '3686839edec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('original',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('original',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
