"""empty message

Revision ID: 677cc913842e
Revises: c0d1665a4362
Create Date: 2025-05-16 10:50:11.902442

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '677cc913842e'
down_revision = 'c0d1665a4362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_index('ix_url_map_short')

    op.drop_table('url_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.TEXT(), nullable=False),
    sa.Column('short', sa.VARCHAR(length=16), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.create_index('ix_url_map_short', ['short'], unique=False)

    # ### end Alembic commands ###
